urls.py
from django.conf.urls import url
from . import views

app_name = 'pylims'
urlpatterns = [
    # the index page
    url(r'^$', views.index, name="index"),
    url(r'^project/$', views.ProjectListView.as_view(), name="project_list"),
    url(r'^project/(?P<pk>[0-9]+)$', views.ProjectDetailView.as_view(), name="project_detail"),
    url(r'^location/$', views.LocationListView.as_view(), name="location_list"),
    url(r'^location/(?P<pk>[0-9]+)$', views.LocationDetailView.as_view(), name="location_detail"),
    url(r'^parameter/$', views.ParameterListView.as_view(), name="parameter_list"),
    url(r'^parameter/(?P<pk>[0-9]+)$', views.ParameterDetailView.as_view(), name="parameter_detail"),
    url(r'^user/$', views.UserListView.as_view(), name="user_list"),
    url(r'^user/(?P<pk>[0-9]+)$', views.UserDetailView.as_view(), name="user_detail"),
    url(r'^sample/$', views.SampleListView.as_view(), name="sample_list"),
    url(r'^sample/add$', views.SampleCreateView.as_view(), name="sample_create"),
    url(r'^sample/import$', views.SampleImportView.as_view(), name="sample_import"),
    url(r'^data_import/$', views.DataImportListView.as_view(), name="data_import_list"),
    url(r'^data_import/(?P<pk>[0-9]+)$', views.DataImportDetailView.as_view(), name="data_import_detail"),
    url(r'^data_import/(?P<pk>[0-9]+)/apply$', views.apply_data_import, name="data_import_apply"),
    url(r'^sample/(?P<pk>[0-9]+)$', views.SampleDetailView.as_view(), name="sample_detail"),
]

models.py
import json
import datetime

from django.db import models
from django.core import serializers
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.text import slugify
import reversion

from . import data_import


def pretty_json(obj):
    jsstr = serializers.serialize("json", [obj, ])
    return json.dumps(json.loads(jsstr)[0], indent=4)


class TagsField(models.TextField):
    """
    This custom field is only valid if the text is valid JSON
    """

    def __init__(self, *args, **kwargs):
        kwargs['blank'] = True
        self.type = kwargs["type"] if "type" in kwargs else None
        super(TagsField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        """Make sure value is valid JSON or '' or None"""
        if value:
            try:
                val = json.loads(value)
                if self.type:
                    if not isinstance(val, self.type):
                        raise ValidationError("Object is not of type %s" % self.type)
                return value
            except ValueError as e:
                raise ValidationError("Invalid JSON: %s" % e)
        else:
            return value

    @staticmethod
    def parse(value, out_type=None):
        if value:
            return json.loads(value)
        elif not value and callable(out_type):
            return out_type()
        else:
            return None


class Project(models.Model):
    name = models.CharField(max_length=55, unique=True)
    slug = models.SlugField(unique=True)
    parent = models.ForeignKey('self', on_delete=models.PROTECT, null=True, blank=True)

    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, editable=False)
    created = models.DateTimeField("created", auto_now_add=True)
    modified = models.DateTimeField("modified", auto_now=True)
    data_import = models.ForeignKey('DataImport', on_delete=models.SET_NULL,
                                    null=True, blank=True, editable=False)

    description = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Project, self).save(*args, **kwargs)

    def as_json(self):
        return pretty_json(self)

    def __str__(self):
        return self.name


class ProjectTag(models.Model):
    parent = models.ForeignKey(Project, on_delete=models.CASCADE)
    key = models.SlugField(max_length=55)
    value = models.TextField(blank=False)
    data_import = models.ForeignKey('DataImport', on_delete=models.SET_NULL,
                                    null=True, blank=True, editable=False)

    def save(self, *args, **kwargs):
        # update parent param modified tag
        self.parent.modified = datetime.datetime.now()
        super(ProjectTag, self).save(*args, **kwargs)

    def __str__(self):
        return '%s="%s"' %(self.key, self.value)


class Location(models.Model):
    name = models.CharField(max_length=55, unique=True)
    slug = models.SlugField(unique=True)
    parent = models.ForeignKey('self', on_delete=models.PROTECT, null=True, blank=True)

    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, editable=False)
    created = models.DateTimeField("created", auto_now_add=True)
    modified = models.DateTimeField("modified", auto_now=True)
    data_import = models.ForeignKey('DataImport', on_delete=models.SET_NULL,
                                    null=True, blank=True, editable=False)

    description = models.TextField(blank=True)
    geometry = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Location, self).save(*args, **kwargs)

    def as_json(self):
        return pretty_json(self)

    def __str__(self):
        return self.name


class LocationTag(models.Model):
    parent = models.ForeignKey(Location, on_delete=models.CASCADE)
    key = models.SlugField(max_length=55)
    value = models.TextField(blank=False)
    data_import = models.ForeignKey('DataImport', on_delete=models.SET_NULL,
                                    null=True, blank=True, editable=False)

    def save(self, *args, **kwargs):
        # update parent param modified tag
        self.parent.modified = datetime.datetime.now()
        super(LocationTag, self).save(*args, **kwargs)

    def __str__(self):
        return '%s="%s"' %(self.key, self.value)


class Sample(models.Model):
    name = models.CharField(max_length=255, blank=True)
    slug = models.CharField(max_length=55, unique=True, editable=False)
    parent = models.ForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, editable=False)

    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, editable=False)
    created = models.DateTimeField("created", auto_now_add=True)
    modified = models.DateTimeField("modified", auto_now=True)
    data_import = models.ForeignKey('DataImport', on_delete=models.SET_NULL,
                                    null=True, blank=True, editable=False)

    collected = models.DateTimeField("collected", blank=True, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
    location = models.ForeignKey(Location, on_delete=models.PROTECT, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.set_slug()
        super(Sample, self).save(*args, **kwargs)

    def set_slug(self):
        dt = self.collected if self.collected else self.created if self.created else datetime.datetime.now()
        location_slug = self.location.slug[:10] if self.location else ""
        user = self.user.username if self.user else ""
        hint = slugify(self.name)

        for date_fun in [self.short_date, self.long_date, self.longest_date]:
            dt_str = date_fun(dt)
            id_str = "_".join(item for item in [user, dt_str, location_slug, hint] if item)
            id_str = id_str[:55]
            other_objects = Sample.objects.filter(slug = id_str)
            if len(other_objects) == 0:
                self.slug = id_str
                return

        self.slug = str(self.pk)

    def short_date(self, dt):
        return str(dt.date())

    def long_date(self, dt):
        return "%sT%s.%s.%s" % (dt.date(), dt.hour, dt.minute, dt.second)

    def longest_date(self, dt):
        return ("%sT%s" % (dt.date(), dt.time())).replace(":", ".")

    def as_json(self):
        return pretty_json(self)

    def __str__(self):
        return self.slug


class SampleTag(models.Model):
    parent = models.ForeignKey(Sample, on_delete=models.CASCADE)
    key = models.SlugField(max_length=55)
    value = models.TextField(blank=False)
    data_import = models.ForeignKey('DataImport', on_delete=models.SET_NULL,
                                    null=True, blank=True, editable=False)

    def save(self, *args, **kwargs):
        # update parent param modified tag
        self.parent.modified = datetime.datetime.now()
        super(SampleTag, self).save(*args, **kwargs)

    def __str__(self):
        return '%s="%s"' %(self.key, self.value)


class Parameter(models.Model):
    name = models.CharField(max_length=55, unique=True)
    slug = models.SlugField(unique=True)
    parent = models.ForeignKey('self', on_delete=models.PROTECT, null=True, blank=True)

    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    created = models.DateTimeField("created", auto_now_add=True)
    modified = models.DateTimeField("modified", auto_now=True)
    data_import = models.ForeignKey('DataImport', on_delete=models.SET_NULL,
                                    null=True, blank=True, editable=False)

    description = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Parameter, self).save(*args, **kwargs)

    def as_json(self):
        return pretty_json(self)

    def __str__(self):
        return self.slug if self.slug else self.name


class ParameterTag(models.Model):
    parent = models.ForeignKey(Parameter, on_delete=models.CASCADE)
    key = models.SlugField(max_length=55)
    value = models.TextField(blank=False)
    data_import = models.ForeignKey('DataImport', on_delete=models.SET_NULL,
                                    null=True, blank=True, editable=False)

    def save(self, *args, **kwargs):
        # update parent param modified tag
        self.parent.modified = datetime.datetime.now()
        super(ParameterTag, self).save(*args, **kwargs)

    def __str__(self):
        return '%s="%s"' %(self.key, self.value)


class Measurement(models.Model):
    param = models.ForeignKey(Parameter, on_delete=models.PROTECT)
    sample = models.ForeignKey(Sample, on_delete=models.CASCADE)
    value = models.TextField(blank=True, null=True)
    tags = TagsField()

    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, editable=False)
    created = models.DateTimeField("created", auto_now_add=True)
    modified = models.DateTimeField("modified", auto_now=True)
    data_import = models.ForeignKey('DataImport', on_delete=models.SET_NULL,
                                    null=True, blank=True, editable=False)

    def parse_tags(self):
        return json.load(self.tags)

    def set_tags(self, **kwargs):
        tags_dict = self.parse_tags()
        for key, value in kwargs.items():
            tags_dict[key] = value
        self.tags = json.dumps(tags_dict)

    def as_json(self):
        return pretty_json(self)

    def __str__(self):
        if self.tags:
            str_out = "%s = %s %s" % (self.param, self.value, self.tags)
            # limit output to 150 chars or so
            if len(str_out) > 147:
                return str_out[:147] + "..."
            else:

templates/pylims/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CWRS LIMS | {% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
    <div id="container">
        <div id="header">
            <div id="branding">
                <h1 id="site-name"><a href="{% url 'pylims:index' %}">CWRS LIMS</a></h1>
            </div>
            <div id="user-tools">
                <p>User tool info here</p>
            </div>
        </div>
        <div id="content", class="colMS">
            <h1>{% block content_title %}{% endblock %}</h1>
            <div id="content-main">
                {% block content_main %}{% endblock %}
            </div>
            <div id="content-related">
                {% block content_related %}{% endblock %}
            </div>
            <br class="clear"/>
        </div>
        <div id="footer">
            {% block footer %}{% endblock %}
        </div>
    </div>
</body>
</html>

templates/pylims/data_import.html
{% extends "pylims/base.html" %}

{% block title %}{{ dataimport }}{% endblock %}

{% block content_title %}Data Import: {{ dataimport }}{% endblock %}

{% block content_main %}
    <pre>
        {{ dataimport.as_json }}
    </pre>

    {% if not dataimport.applied %}
        <form action="{% url 'pylims:data_import_apply' dataimport.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Apply Import" />
        </form>
    {% endif %}

    {% include "pylims/data_import_table.html" %}

{% endblock %}

{% block content_related %}

    <div class="content-related-actions">
        <h3>User Actions</h3>
        <ul>
            <li>(None yet)</li>
        </ul>
    </div>
    <div class="content-related-actions">
        <h3>Admin Actions</h3>
        <ul>
            <li><a href="{% url 'admin:pylims_dataimport_change' dataimport.id %}">Admin View</a></li>
        </ul>
    </div>

{% endblock %}

templates/pylims/data_import_table.html
{% if dataimport.applied %}

    {% include 'pylims/sample_table.html' %}

{% else %}

    {% if sample_list_title %}<h1>{{ sample_list_title }}</h1>{% endif %}

    {% if sample_list %}
            <table class="object-list">
                <thead>
                    <tr>
                        <th>Sample ID</th>
                        <th>User</th>
                        <th>Project</th>
                        <th>Location</th>
                        <th>Tags</th>
                    </tr>
                </thead>
            {% for sample in sample_list %}
                <tr>
                    <td>
                        {% if sample.pk %}
                        <a href="{% url 'pylims:sample_detail' sample.id %}">{{ sample.slug }}</a>
                        {% else %}
                        {{ sample.slug }}
                        {% endif %}
                    </td>
                    <td>
                        {% if sample.user %}
                        <a href="{% url 'pylims:user_detail' user.id %}">{{ sample.user }}</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if sample.project %}
                        <a href="{% url 'pylims:project_detail' sample.project.id %}">{{ sample.project }}</a>
                        {% endif %}
                    </td>
                    <td>{% if sample.location %}
                        <a href="{% url 'pylims:location_detail' sample.location.id %}">{{ sample.location }}</a>
                        {% endif %}
                    </td>
                    <td>
                        {% for tag in sample.import_tags %}
                             {{ tag }} <br/>
                        {% endfor %}
                    </td>
                </tr>

            {% endfor %}
            </table>
        {% else %}
            <p>No samples are available.</p>
        {% endif %}

{% endif %}

templates/pylims/location_list.html
{% extends "pylims/base.html" %}

{% block title %}Locations{% endblock %}

{% block content_title %}Locations{% endblock %}

{% block content_main %}

    {% if location_list %}
        <ul>
        {% for location in location_list %}
            <li><a href="{% url 'pylims:location_detail' location.id %}">{{ location.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No locations are available.</p>
    {% endif %}

{% endblock %}

templates/pylims/parameter_list.html
{% extends "pylims/base.html" %}

{% block title %}Parameters{% endblock %}

{% block content_title %}Parameters{% endblock %}

{% block content_main %}

    {% if parameter_list %}
        <ul>
        {% for parameter in parameter_list %}
            <li><a href="{% url 'pylims:parameter_detail' parameter.id %}">{{ parameter.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No sample meta keys are available.</p>
    {% endif %}

{% endblock %}

{% block content_related %}

    <div class="content-related-actions">
        <h3>User Actions</h3>
        <ul>
            <li>(None yet)</li>
        </ul>
    </div>
    <div class="content-related-actions">
        <h3>Admin Actions</h3>
        <ul>
            <li><a href="{% url 'admin:pylims_parameter_changelist' %}">Admin View</a></li>
        </ul>
    </div>

{% endblock %}

templates/pylims/sample.html
{% extends "pylims/base.html" %}

{% block title %}{{ sample.sample_id }}{% endblock %}

{% block content_title %}Sample: {{ sample.sample_id }}{% endblock %}

{% block content_main %}

    <pre>
        {{ sample.as_json }}
    </pre>

{% endblock %}

templates/pylims/sample_form.html
{% extends "pylims/base.html" %}

{% block title %}New Sample{% endblock %}

{% block content_title %}New Sample{% endblock %}

{% block content_main %}

    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" />
    </form>

{% endblock %}

{% block content_related %}

    <div class="content-related-actions">
        <h3>User Actions</h3>
        <ul>
            <li>(None yet)</li>
        </ul>
    </div>
    <div class="content-related-actions">
        <h3>Admin Actions</h3>
        <ul>
            <li><a href="{% url 'admin:pylims_sample_add' %}">Admin View</a></li>
        </ul>
    </div>

{% endblock %}

templates/pylims/sample_import_form.html
{% extends "pylims/base.html" %}

{% block title %}Import Samples{% endblock %}

{% block content_title %}Import Samples{% endblock %}

{% block content_main %}

    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" />
    </form>

{% endblock %}

{% block content_related %}

    <div class="content-related-actions">
        <h3>User Actions</h3>
        <ul>
            <li>(None yet)</li>
        </ul>
    </div>
    <div class="content-related-actions">
        <h3>Admin Actions</h3>
        <ul>
            <li>(None yet)</li>
        </ul>
    </div>

{% endblock %}

templates/pylims/sample_list.html
{% extends "pylims/base.html" %}

{% block title %}Samples{% endblock %}

{% block content_title %}Samples{% endblock %}

{% block content_main %}

    {% include "pylims/sample_table.html" %}

{% endblock %}


{% block content_related %}

    <div class="content-related-actions">
        <h3>User Actions</h3>
        <ul>
            <li><a href="{% url 'pylims:sample_create' %}">New Sample</a></li>
            <li><a href="{% url 'pylims:sample_import' %}">Import Samples</a></li>
        </ul>
    </div>
    <div class="content-related-actions">
        <h3>Admin Actions</h3>
        <ul>
            <li><a href="{% url 'admin:pylims_sample_changelist' %}">Admin View</a></li>
        </ul>
    </div>

{% endblock %}

templates/pylims/sample_table.html
{% if sample_list_title %}<h1>{{ sample_list_title }}</h1>{% endif %}

{% if sample_list %}
        <table class="object-list">
            <thead>
                <tr>
                    <th>Sample ID</th>
                    <th>User</th>
                    <th>Project</th>
                    <th>Location</th>
                    <th>Modified</th>
                    <th>Tags</th>
                    <th>Measurements</th>
                </tr>
            </thead>
        {% for sample in sample_list %}
            <tr>
                <td>
                    {% if sample.pk %}
                    <a href="{% url 'pylims:sample_detail' sample.id %}">{{ sample.slug }}</a>
                    {% else %}
                    {{ sample.slug }}
                    {% endif %}
                </td>
                <td>
                    {% if sample.user %}
                    <a href="{% url 'pylims:user_detail' user.id %}">{{ sample.user }}</a>
                    {% endif %}
                </td>
                <td>
                    {% if sample.project %}
                    <a href="{% url 'pylims:project_detail' sample.project.id %}">{{ sample.project }}</a>
                    {% endif %}
                </td>
                <td>{% if sample.location %}
                    <a href="{% url 'pylims:location_detail' sample.location.id %}">{{ sample.location }}</a>
                    {% endif %}
                </td>
                <td>{{ sample.modified }}</td>
                <td>
                    {% for tag in sample.sampletag_set.all %}
                      {{ tag }} <br/>
                    {% endfor %}
                </td>
                <td>
                    {% for measurement in sample.measurement_set.all %}
                        <a href="{% url 'pylims:parameter_detail' measurement.param.id %}">{{ measurement.param }}</a> = {{ measurement.value }}
                        {% if measurement.tags %} {{ measurement.tags }} {% endif %}<br/>
                    {% endfor %}
                </td>
            </tr>

        {% endfor %}
        </table>
    {% else %}
        <p>No samples are available.</p>
    {% endif %}

templates/pylims/samplemetakey.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sample Meta Key: {{ samplemetakey.name }}</title>
</head>
<body>

<h1>{{ samplemetakey.name }}</h1>

<pre>
    {{ samplemetakey.as_json }}
</pre>

</body>
</html>

templates/pylims/samplemetakey_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sample Meta Keys</title>
</head>
<body>

{% if samplemetakey_list %}
    <ul>
    {% for samplemetakey in samplemetakey_list %}
        <li><a href="{% url 'pylims:samplemetakey_detail' samplemetakey.id %}">{{ samplemetakey.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No sample meta keys are available.</p>
{% endif %}


</body>
</html>

templates/pylims/user.html
{% extends "pylims/base.html" %}

{% block title %}{{ user.username }}{% endblock %}

{% block content_title %}User: {{ user.username }}{% endblock %}

{% block content_main %}

    <pre>
        {{ user.username }}
    </pre>

    {% include "pylims/sample_table.html" %}

{% endblock %}

{% block content_related %}

    <div class="content-related-actions">
        <h3>User Actions</h3>
        <ul>
            <li>(None yet)</li>
        </ul>
    </div>
    <div class="content-related-actions">
        <h3>Admin Actions</h3>
        <ul>
            <li><a href="{% url 'admin:auth_user_change' user.id %}">Admin View</a></li>
        </ul>
    </div>

{% endblock %}

templates/pylims/user_list.html
{% extends "pylims/base.html" %}

{% block title %}Users{% endblock %}

{% block content_title %}Users{% endblock %}

{% block content_main %}

    {% if user_list %}
        <ul>
        {% for user in user_list %}
            <li><a href="{% url 'pylims:user_detail' user.id %}">{{ user.username }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No users are available.</p>
    {% endif %}

{% endblock %}

{% block content_related %}

    <div class="content-related-actions">
        <h3>User Actions</h3>
        <ul>
            <li>(None yet)</li>
        </ul>
    </div>
    <div class="content-related-actions">
        <h3>Admin Actions</h3>
        <ul>
            <li><a href="{% url 'admin:auth_user_changelist' %}">Admin View</a></li>
        </ul>
    </div>

{% endblock %}